blank_issues_enabled: false
contact_links:
  - name: Help / Questions
    url: https://github.com/orgs/Hidden-Alchemy/discussions/categories/help
    about: For open-ended questions that are not bugs, features, or ideas.